// Bilingual content for The Dieng Group (Meridian edition).
// EN is the default; FR is the toggle. Non-translatable values (image paths,
// hrefs, names, hex) are repeated per locale to keep components simple.

export type Lane = "navy" | "teal" | "amber";
export const locales = ["en", "fr"] as const;
export type Locale = (typeof locales)[number];

const site = {
  name: "The Dieng Group",
  address: "Historic Meridian Park District, Indianapolis, IN 46205",
  phone: "+1 (201) 286-1907",
  email: "info@thedienggroup.com",
  web: "www.thedienggroup.com",
};

const social = [
  { label: "LinkedIn", href: "#" },
  { label: "YouTube", href: "#" },
  { label: "Instagram", href: "#" },
  { label: "Facebook", href: "#" },
];

const teamPhotos = {
  nefferitti: "/images/team/nefferitti.jpg",
  iqra: "/images/team/iqra.jpg",
  dorcas: "/images/team/dorcas.jpg",
  daniel: "/images/team/daniel.jpg",
  stephanie: "/images/team/stephanie.jpg",
};

const en = {
  site,
  social,
  ui: {
    cta: "Start a conversation",
    getInTouch: "Start a conversation",
    readDispatch: "Read the Dispatch",
    enterLane: "Enter this lane",
    subscribe: "Subscribe",
    download: "Download the brief (PDF)",
    inThisIssue: "In this issue",
    inThisIssueLead: "The Dieng Group, read like the publication it is — start anywhere.",
    closingTitle: "Bring us the ground you're standing on.",
    menu: "Menu",
    theme: "Toggle theme",
    lang: "Français",
    heroEyebrow: "Consulting · Trade · Development",
    exploreServices: "Explore our services",
    viewProfile: "View profile",
    close: "Close",
  },
  homeIssue: [
    { n: "01", label: "About", href: "/about", line: "What guides us — mission, vision, and the values we won't compromise." },
    { n: "02", label: "Services", href: "/services", line: "Three umbrellas of work, scaled from Silver to Diamond, read through the SPELIT lens." },
    { n: "03", label: "Our Impact", href: "/impact", line: "Field notes, not figures — the work as it actually lands on the ground." },
    { n: "04", label: "The Team", href: "/team", line: "The people who file this dispatch, in their own words." },
    { n: "05", label: "The Dispatch", href: "/dispatch", line: "Our newsletter and the gated PDF brief from the corridor." },
    { n: "06", label: "Contact", href: "/contact", line: "Tell us where you operate. We'll meet you there." },
  ],
  nav: [
    { label: "About", href: "/about" },
    { label: "Services", href: "/services" },
    { label: "Impact", href: "/impact" },
    { label: "Team", href: "/team" },
    { label: "Podcast", href: "/podcast" },
    { label: "Dispatch", href: "/dispatch" },
    { label: "Contact", href: "/contact" },
  ],
  hero: {
    kicker: "Dispatch No. 01 · Meridian Park, Indianapolis",
    title: "We bring organizations closer to the people and partners they trade with.",
    standfirst:
      "A consulting, import and export firm working the corridor between the American Midwest and West Africa — starting in Senegal and The Gambia.",
  },
  dateline: "Historic Meridian Park · Indianapolis",
  route: [
    { place: "Indianapolis", note: "Home desk · Meridian Park" },
    { place: "Orlando / Miami", note: "with Agromad LLC" },
    { place: "Port-au-Prince", note: "Trade corridor" },
    { place: "Dakar", note: "Senegal" },
    { place: "Banjul · Serekunda", note: "The Gambia" },
  ],
  routeKicker: "The corridor we work",
  expansion: "East Africa · Europe · India",
  about: {
    kicker: "What guides us",
    standfirst:
      "We don't arrive with a playbook. We arrive with a way of reading the ground — and a short list of things we will not compromise.",
    infographicCaption: "Mission · Vision · Core values",
  },
  values: [
    { title: "Contextual intelligence", body: "We read the social, political, economic, legal, intercultural and technological ground before we advise. Every engagement starts with the environment, not a template." },
    { title: "Tailored excellence", body: "No one-size-fits-all. From a first-time grantee to a national agency, the work is sized to the organization in front of us." },
    { title: "Collaborative partnership", body: "We sit on the same side of the table as our clients — transparent, responsive, and accountable to the outcome, not the invoice." },
    { title: "Integrity & compliance", body: "Due diligence and regulatory adherence are not afterthoughts. They protect our clients and the public trust they answer to." },
    { title: "Evidence over assertion", body: "We let reporting, analysis and named outcomes carry the argument — never a number invented to impress." },
    { title: "Adaptive reach", body: "We grow our capability through partnerships rather than overreach, extending where our clients need us without diluting the core." },
    { title: "Sector fluency", body: "We speak the distinct languages of private enterprise, civil society and government — and translate between them." },
  ],
  serve: {
    kicker: "Who we serve",
    standfirst: "Three audiences, three different pressures. Find your lane — the colour follows you through the rest of the page.",
  },
  lanes: [
    { lane: "navy" as Lane, name: "Private & corporate", numeral: "01", image: "/images/trade-port.jpg", caption: "Atlantic corridor · import & export", line: "For enterprises moving goods, people and capital across borders, we sharpen operations, compliance and the decisions in between.", services: ["Program & grant management", "Workforce planning", "Change management", "Compliance & auditing (HR)", "Reporting & data analytics"] },
    { lane: "teal" as Lane, name: "NGOs & non-profits", numeral: "02", image: "/images/community-joal.jpg", caption: "Joal-Fadiouth · Senegal", line: "For organizations whose budget is a promise to a community, we turn every resource into delivered mission.", services: ["Program & grant management", "Workforce planning", "Change management", "Compliance & audit", "Reporting & data analytics"] },
    { lane: "amber" as Lane, name: "Government agencies", numeral: "03", image: "/images/agriculture-field.jpg", caption: "Sourcing & rural development", line: "For agencies answerable to the public, we help attract investment, shape policy, and execute contracts that hold up to scrutiny.", services: ["Foreign direct investment (FDI)", "Regulatory, compliance & risk", "Policy & governance", "Contracting & negotiation"] },
  ],
  approach: {
    kicker: "Our approach",
    title: "The SPELIT lens.",
    caption: "Serekunda · The Gambia",
  },
  spelit: {
    standfirst: "Before a single recommendation, we scan six environments. It is the lens behind every engagement — and the signature of how we think.",
    segments: [
      { letter: "S", word: "Social", gloss: "Workforce demographics, organizational culture, the community an organization answers to." },
      { letter: "P", word: "Political", gloss: "Government stability, policy shifts, the regulatory weather ahead." },
      { letter: "E", word: "Economic", gloss: "Market conditions, funding climate, the appetite for investment." },
      { letter: "L", word: "Legal", gloss: "Compliance obligations, contractual exposure, what the rules actually require." },
      { letter: "I", word: "Intercultural", gloss: "Cross-cultural dynamics and the realities of operating across borders." },
      { letter: "T", word: "Technological", gloss: "Data systems, automation, the tools that decide what is possible." },
    ],
  },
  services: {
    kicker: "Services",
    standfirst: "Three umbrellas of work, plus the specialists we bring in. Priced to the organization, never to a template — and never to a number on this page.",
    tiersKicker: "Right-sized engagement",
    extendedKicker: "Extended services",
  },
  tiers: [
    { name: "Silver", note: "Emerging organizations — the essential core, done properly." },
    { name: "Gold", note: "Established teams — expanded capability and reporting." },
    { name: "Platinum", note: "Large operations — dedicated support and deeper analysis." },
    { name: "Diamond", note: "Singular mandates — built entirely around the client." },
  ],
  partnerServices: {
    line: "Beyond our core, delivered through trusted partners.",
    items: ["Due diligence & vetting", "Financial auditing", "Legal counsel — via MOU with law firms", "Import & export — with Agromad LLC"],
  },
  impact: {
    kicker: "Our impact",
    standfirst: "We don't keep score on a wall. The work shows up as relationships kept and goods that arrive — so here it is as field notes, not figures.",
  },
  fieldNotes: [
    { tag: "Field note · Serekunda, The Gambia", image: "/images/market-serrekunda.jpg", title: "Where a fair price is the whole strategy", body: "In a market where a handshake still sets the terms, we work so that suppliers are paid fairly and goods are sourced ethically — the quiet groundwork that makes a trade relationship last." },
    { tag: "Field note · Joal-Fadiouth, Senegal", image: "/images/community-joal.jpg", title: "Mission measured in delivery, not dashboards", body: "For the organizations we serve, impact is a program that reaches the people it promised — counted in commitments kept, not figures on a wall." },
    { tag: "Field note · The Atlantic corridor", image: "/images/artisan-craft.jpg", title: "Bringing a craft to a wider market", body: "From a workshop to a buyer an ocean away, we help the work of skilled hands cross borders with the paperwork, partners and standards it needs to arrive." },
  ],
  team: {
    kicker: "The contributors",
    standfirst: "Real people file this dispatch — advisory, programs, strategy and the field.",
    pending: "Headshot to come",
    members: [
      { name: "Nefferitti Dieng", role: "Founder & President", fluency: "Global Governmental Agency (GGA)", image: teamPhotos.nefferitti, bio: "Founder and President of The Dieng Group, leading the Global Governmental Agency (GGA) sector. She brings policy and governance expertise across small- to medium-scale foreign direct investment (FDI), with development, implementation, evaluation and compliance for organizations and governmental bodies." },
      { name: "Dr. Dorcas Mworsho, PhD", role: "Managing Director, Global Private Industry", fluency: "Org. development · Change · MEL", image: teamPhotos.dorcas, bio: "Managing Director of the Global Private Industry (GPI) sector, with over 20 years in organizational management and program implementation and more than a decade of university teaching. She holds a PhD in Global Leadership and Change (Pepperdine) and specializes in organizational development, change management, and monitoring, evaluation & learning — grounded in servant leadership and inclusive, community-centred practice." },
      { name: "Dr. Daniel Sugamo, PhD", role: "Vice-President, Global Strategic Strategies", fluency: "SPELIT · Strategy · Conflict resolution", image: teamPhotos.daniel, bio: "Vice-President of the Global Strategic Strategies sector. A conflict-resolution specialist and systemic, strategic consultant with over a decade of international experience driving transformative change across organizational systems, he architects the firm's strategic frameworks — including the SPELIT environmental-scanning model." },
      { name: "Dr. Iqra Ameen", role: "Advisory & Research", fluency: "Research rigor · Due diligence", image: teamPhotos.iqra, bio: "Holds a PhD in Organic Chemistry from The Women's University, Multan, with research in advanced nanocomposite catalysis. She brings scientific rigor and analytical discipline to the firm's evidence-based advisory and due-diligence work." },
      { name: "Dr. Stephanie F. Wanza", role: "Leadership & Community Advisory", fluency: "Leadership · Community · Equity", image: teamPhotos.stephanie, bio: "Holds a Doctorate in Global Leadership and Change from Pepperdine University. A pastor, counselor, teacher and community advocate, she champions access to mental health and the reduction of disparities in marginalized communities." },
      { name: "Ibrahim Kamara", role: "Business Development & Operations", fluency: "Market expansion · Partnerships", image: null, bio: "A business-development strategist, operations leader and university lecturer with a track record of driving growth and building high-impact partnerships across West Africa — spanning consulting, market research, mobility, education and digital sectors." },
    ],
  },
  dispatch: {
    kicker: "The Meridian Dispatch · Issue 01",
    sectionKicker: "The Meridian Dispatch",
    title: "West Africa market & advisory notes",
    blurb: "A periodic brief from the corridor — what we are seeing in Senegalese and Gambian markets, and what it means for organizations trading with the region. Signed by the whole team at The Dieng Group.",
    cover: "/images/infographics/scope-expansion.png",
    download: "Download the brief (PDF)",
    browseNote: "Browse freely — we'll only ask for a few details at download.",
    subscribeLabel: "Subscribe to the Dispatch",
    newsletterNote: "Prefer it in your inbox? Subscribe and we'll send a short note to confirm — written by the whole team at The Dieng Group.",
    subscribedThanks: "Thank you — check your inbox to confirm your subscription. The note is signed by the whole team.",
    modalTitle: "A few details, then it's yours.",
    modalDoneKicker: "Ready",
    modalDoneTitle: "Your copy is on its way.",
    modalDoneBody: "The Meridian Dispatch, Issue 01 would download now — and a confirmation would arrive in your inbox.",
    optIn: "Also send me the newsletter (double opt-in — we'll email to confirm).",
  },
  podcast: {
    kicker: "On air",
    title: "From the corridor, out loud.",
    standfirst: "Conversations from the desk and the field — what we hear in markets and ministries, in plain language.",
    comingSoon: "Coming soon",
    episodes: [
      "Reading the ground before the deal",
      "A fair price as a business strategy",
      "What governments get wrong about investment",
    ],
  },
  contact: {
    kicker: "Contact",
    sectionKicker: "Contact",
    title: "Tell us where you operate. We'll meet you there.",
    standfirst: "The first question we ask is never “what's your budget” — it's “what's the ground you're standing on.”",
    homeDesk: "Home desk",
    corridor: "On the corridor",
    reach: "Reach us",
    nameLabel: "Your name",
    emailLabel: "Email",
    orgLabel: "Type of organization",
    needLabel: "What brings you here",
    regionLabel: "Where you operate",
    tierLabel: "Scale of engagement",
    msgLabel: "A line about the work",
    msgPlaceholder: "What are you trying to do, and where?",
    send: "Send your note",
    expandingNote: "Expanding to East Africa · Europe · India.",
    sentTitle: "Thank you — your note is with us.",
    sentBody: "Someone from the team will write back, not a bot. Talk soon.",
    select: "Select…",
  },
  forms: {
    fullName: "Full name",
    sector: "Sector / profession",
    phone: "Phone number",
    emailAddress: "Email address",
  },
  sectors: ["Private / Corporate", "NGO / Non-profit", "Government agency", "Education", "Healthcare", "Finance", "Agriculture & trade", "Other"],
  probing: {
    orgType: ["Private / Corporate", "NGO / Non-profit", "Government agency", "Other"],
    need: ["Program & grant management", "Workforce planning", "Change management", "Compliance & auditing", "Reporting & data analytics", "Foreign direct investment", "Policy & governance", "Contracting & negotiation", "Due diligence", "Import / export"],
    region: ["United States", "Senegal", "The Gambia", "West Africa (other)", "East Africa", "Haiti / Caribbean", "Europe", "India", "Other"],
    engagement: ["Silver", "Gold", "Platinum", "Diamond", "Not sure yet"],
  },
  footer: {
    blurb: "A consulting, import and export firm working the corridor between the American Midwest and West Africa.",
    sections: "Sections",
    desk: "The desk",
    rights: "All rights reserved.",
  },
  b2: {
    serveTitle: "Three sectors, one disciplined approach.",
    servicesTitle: "Capabilities across three umbrellas.",
    impactTitle: "Measured in outcomes, not numbers.",
    teamTitle: "Advisors who have done the work.",
    teamLead: "A team fluent across the private, civil and public sectors — and across the markets we serve.",
    aboutEyebrow: "Who we are",
    aboutTitle: "Three branches, one purpose.",
    aboutLead: "The Dieng Group is a consulting, import and export firm headquartered in Indianapolis, working to bring organizations in developing markets closer to the world they trade with.",
    coreValues: "Our core values",
  },
};

const fr: typeof en = {
  site,
  social,
  ui: {
    cta: "Démarrer la conversation",
    getInTouch: "Démarrer la conversation",
    readDispatch: "Lire la Dispatch",
    enterLane: "Entrer dans cette voie",
    subscribe: "S'abonner",
    download: "Télécharger le dossier (PDF)",
    inThisIssue: "Dans ce numéro",
    inThisIssueLead: "The Dieng Group, à lire comme la publication qu'il est — commencez où vous voulez.",
    closingTitle: "Parlez-nous du terrain sur lequel vous êtes.",
    menu: "Menu",
    theme: "Changer de thème",
    lang: "English",
    heroEyebrow: "Conseil · Commerce · Développement",
    exploreServices: "Découvrir nos services",
    viewProfile: "Voir le profil",
    close: "Fermer",
  },
  homeIssue: [
    { n: "01", label: "À propos", href: "/about", line: "Ce qui nous guide — mission, vision et les valeurs sur lesquelles nous ne transigeons pas." },
    { n: "02", label: "Services", href: "/services", line: "Trois grands domaines de travail, du Silver au Diamond, lus à travers le prisme SPELIT." },
    { n: "03", label: "Notre impact", href: "/impact", line: "Des notes de terrain, pas des chiffres — le travail tel qu'il atterrit vraiment." },
    { n: "04", label: "L'équipe", href: "/team", line: "Les personnes qui signent cette dispatch, dans leurs propres mots." },
    { n: "05", label: "La Dispatch", href: "/dispatch", line: "Notre newsletter et le dossier PDF depuis le corridor." },
    { n: "06", label: "Contact", href: "/contact", line: "Dites-nous où vous opérez. Nous vous y rejoindrons." },
  ],
  nav: [
    { label: "À propos", href: "/about" },
    { label: "Services", href: "/services" },
    { label: "Impact", href: "/impact" },
    { label: "Équipe", href: "/team" },
    { label: "Podcast", href: "/podcast" },
    { label: "Dispatch", href: "/dispatch" },
    { label: "Contact", href: "/contact" },
  ],
  hero: {
    kicker: "Dispatch n° 01 · Meridian Park, Indianapolis",
    title: "Nous rapprochons les organisations des gens et des partenaires avec qui elles commercent.",
    standfirst:
      "Un cabinet de conseil, d'import et d'export qui travaille le corridor entre le Midwest américain et l'Afrique de l'Ouest — en commençant par le Sénégal et la Gambie.",
  },
  dateline: "Historic Meridian Park · Indianapolis",
  route: [
    { place: "Indianapolis", note: "Bureau · Meridian Park" },
    { place: "Orlando / Miami", note: "avec Agromad LLC" },
    { place: "Port-au-Prince", note: "Corridor commercial" },
    { place: "Dakar", note: "Sénégal" },
    { place: "Banjul · Serekunda", note: "Gambie" },
  ],
  routeKicker: "Le corridor que nous parcourons",
  expansion: "Afrique de l'Est · Europe · Inde",
  about: {
    kicker: "Ce qui nous guide",
    standfirst:
      "Nous n'arrivons pas avec un manuel. Nous arrivons avec une manière de lire le terrain — et une courte liste de choses sur lesquelles nous ne transigeons pas.",
    infographicCaption: "Mission · Vision · Valeurs",
  },
  values: [
    { title: "Intelligence contextuelle", body: "Nous lisons le terrain social, politique, économique, juridique, interculturel et technologique avant de conseiller. Chaque mission part de l'environnement, pas d'un modèle." },
    { title: "Excellence sur mesure", body: "Pas de solution unique. D'un premier bénéficiaire de subvention à une agence nationale, le travail est dimensionné à l'organisation que nous avons en face." },
    { title: "Partenariat collaboratif", body: "Nous sommes du même côté de la table que nos clients — transparents, réactifs, et redevables du résultat, pas de la facture." },
    { title: "Intégrité & conformité", body: "La diligence raisonnable et le respect des règles ne sont pas des détails. Ils protègent nos clients et la confiance publique dont ils répondent." },
    { title: "La preuve avant l'affirmation", body: "Nous laissons le reporting, l'analyse et des résultats nommés porter l'argument — jamais un chiffre inventé pour impressionner." },
    { title: "Portée adaptative", body: "Nous développons nos capacités par des partenariats plutôt que par la surextension, en allant là où nos clients ont besoin de nous sans diluer le cœur du métier." },
    { title: "Maîtrise sectorielle", body: "Nous parlons les langues distinctes de l'entreprise privée, de la société civile et du gouvernement — et nous traduisons entre elles." },
  ],
  serve: {
    kicker: "Qui nous servons",
    standfirst: "Trois publics, trois pressions différentes. Trouvez votre voie — la couleur vous suit dans tout le reste de la page.",
  },
  lanes: [
    { lane: "navy" as Lane, name: "Privé & entreprises", numeral: "01", image: "/images/trade-port.jpg", caption: "Corridor atlantique · import & export", line: "Pour les entreprises qui déplacent biens, personnes et capitaux à travers les frontières, nous affûtons les opérations, la conformité et les décisions entre les deux.", services: ["Gestion de programmes & subventions", "Planification des effectifs", "Conduite du changement", "Conformité & audit (RH)", "Reporting & analyse de données"] },
    { lane: "teal" as Lane, name: "ONG & associations", numeral: "02", image: "/images/community-joal.jpg", caption: "Joal-Fadiouth · Sénégal", line: "Pour les organisations dont le budget est une promesse faite à une communauté, nous transformons chaque ressource en mission accomplie.", services: ["Gestion de programmes & subventions", "Planification des effectifs", "Conduite du changement", "Conformité & audit", "Reporting & analyse de données"] },
    { lane: "amber" as Lane, name: "Agences gouvernementales", numeral: "03", image: "/images/agriculture-field.jpg", caption: "Sourcing & développement rural", line: "Pour les agences responsables devant le public, nous aidons à attirer l'investissement, façonner les politiques et exécuter des contrats qui résistent à l'examen.", services: ["Investissement direct étranger (IDE)", "Réglementation, conformité & risque", "Politiques & gouvernance", "Contractualisation & négociation"] },
  ],
  approach: {
    kicker: "Notre approche",
    title: "Le prisme SPELIT.",
    caption: "Serekunda · Gambie",
  },
  spelit: {
    standfirst: "Avant la moindre recommandation, nous scrutons six environnements. C'est le prisme derrière chaque mission — et la signature de notre façon de penser.",
    segments: [
      { letter: "S", word: "Social", gloss: "Démographie des effectifs, culture organisationnelle, communauté dont l'organisation répond." },
      { letter: "P", word: "Politique", gloss: "Stabilité gouvernementale, virages politiques, le climat réglementaire à venir." },
      { letter: "E", word: "Économique", gloss: "Conditions de marché, climat de financement, appétit pour l'investissement." },
      { letter: "L", word: "Légal", gloss: "Obligations de conformité, exposition contractuelle, ce que les règles exigent vraiment." },
      { letter: "I", word: "Interculturel", gloss: "Dynamiques interculturelles et réalités d'une activité transfrontalière." },
      { letter: "T", word: "Technologique", gloss: "Systèmes de données, automatisation, les outils qui décident du possible." },
    ],
  },
  services: {
    kicker: "Services",
    standfirst: "Trois grands domaines de travail, plus les spécialistes que nous mobilisons. Tarifés à l'organisation, jamais à un modèle — et jamais à un chiffre sur cette page.",
    tiersKicker: "Un engagement à la bonne échelle",
    extendedKicker: "Services étendus",
  },
  tiers: [
    { name: "Silver", note: "Organisations émergentes — l'essentiel, fait correctement." },
    { name: "Gold", note: "Équipes établies — capacités et reporting élargis." },
    { name: "Platinum", note: "Grandes opérations — accompagnement dédié et analyse approfondie." },
    { name: "Diamond", note: "Mandats singuliers — entièrement bâtis autour du client." },
  ],
  partnerServices: {
    line: "Au-delà de notre cœur de métier, via des partenaires de confiance.",
    items: ["Diligence raisonnable & vérification", "Audit financier", "Conseil juridique — via accords avec cabinets d'avocats", "Import & export — avec Agromad LLC"],
  },
  impact: {
    kicker: "Notre impact",
    standfirst: "Nous ne tenons pas de compteur sur un mur. Le travail se voit dans les relations tenues et les marchandises qui arrivent — alors le voici en notes de terrain, pas en chiffres.",
  },
  fieldNotes: [
    { tag: "Note de terrain · Serekunda, Gambie", image: "/images/market-serrekunda.jpg", title: "Quand un prix juste est toute la stratégie", body: "Sur un marché où une poignée de main fixe encore les termes, nous travaillons pour que les fournisseurs soient payés équitablement et les biens sourcés de façon éthique — le travail discret qui fait durer une relation commerciale." },
    { tag: "Note de terrain · Joal-Fadiouth, Sénégal", image: "/images/community-joal.jpg", title: "Une mission mesurée à la livraison, pas au tableau de bord", body: "Pour les organisations que nous servons, l'impact est un programme qui atteint les gens qu'il avait promis d'atteindre — compté en engagements tenus, pas en chiffres sur un mur." },
    { tag: "Note de terrain · Le corridor atlantique", image: "/images/artisan-craft.jpg", title: "Porter un artisanat vers un marché plus vaste", body: "D'un atelier à un acheteur à un océan de distance, nous aidons le travail de mains expertes à franchir les frontières avec les papiers, les partenaires et les normes nécessaires pour arriver." },
  ],
  team: {
    kicker: "Les contributeurs",
    standfirst: "De vraies personnes signent cette dispatch — conseil, programmes, stratégie et terrain.",
    pending: "Portrait à venir",
    members: [
      { name: "Nefferitti Dieng", role: "Fondatrice & Présidente", fluency: "Global Governmental Agency (GGA)", image: teamPhotos.nefferitti, bio: "Fondatrice et Présidente de The Dieng Group, à la tête du secteur Global Governmental Agency (GGA). Elle apporte une expertise en politiques et gouvernance sur l'investissement direct étranger (IDE) de petite et moyenne échelle, avec le développement, la mise en œuvre, l'évaluation et la conformité pour les organisations et corps gouvernementaux." },
      { name: "Dr. Dorcas Mworsho, PhD", role: "Directrice générale, Global Private Industry", fluency: "Développement org. · Changement · MEL", image: teamPhotos.dorcas, bio: "Directrice générale du secteur Global Private Industry (GPI), avec plus de 20 ans en management organisationnel et mise en œuvre de programmes, et plus d'une décennie d'enseignement universitaire. Titulaire d'un PhD en Global Leadership and Change (Pepperdine), elle est spécialiste du développement organisationnel, de la conduite du changement et du suivi-évaluation-apprentissage — ancrée dans le leadership serviteur et une approche inclusive et communautaire." },
      { name: "Dr. Daniel Sugamo, PhD", role: "Vice-Président, Global Strategic Strategies", fluency: "SPELIT · Stratégie · Résolution de conflits", image: teamPhotos.daniel, bio: "Vice-Président du secteur Global Strategic Strategies. Spécialiste de la résolution de conflits et consultant systémique et stratégique fort de plus d'une décennie d'expérience internationale, il conçoit les cadres stratégiques du cabinet — dont le modèle d'analyse environnementale SPELIT." },
      { name: "Dr. Iqra Ameen", role: "Conseil & Recherche", fluency: "Rigueur de recherche · Diligence", image: teamPhotos.iqra, bio: "Titulaire d'un PhD en chimie organique de The Women's University (Multan), avec des recherches sur la catalyse par nanocomposites. Elle apporte rigueur scientifique et discipline analytique au conseil fondé sur les preuves et à la diligence raisonnable du cabinet." },
      { name: "Dr. Stephanie F. Wanza", role: "Leadership & Conseil communautaire", fluency: "Leadership · Communauté · Équité", image: teamPhotos.stephanie, bio: "Titulaire d'un Doctorat en Global Leadership and Change de Pepperdine University. Pasteure, conseillère, enseignante et défenseuse communautaire, elle milite pour l'accès à la santé mentale et la réduction des disparités dans les communautés marginalisées." },
      { name: "Ibrahim Kamara", role: "Développement commercial & Opérations", fluency: "Expansion · Partenariats", image: null, bio: "Stratège en développement commercial, leader opérationnel et enseignant universitaire, avec un bilan de croissance et de partenariats à fort impact en Afrique de l'Ouest — conseil, études de marché, mobilité, éducation et numérique." },
    ],
  },
  dispatch: {
    kicker: "The Meridian Dispatch · Numéro 01",
    sectionKicker: "The Meridian Dispatch",
    title: "Notes de marché & de conseil sur l'Afrique de l'Ouest",
    blurb: "Un dossier périodique depuis le corridor — ce que nous observons sur les marchés sénégalais et gambiens, et ce que cela signifie pour les organisations qui commercent avec la région. Signé par toute l'équipe de The Dieng Group.",
    cover: "/images/infographics/scope-expansion.png",
    download: "Télécharger le dossier (PDF)",
    browseNote: "Naviguez librement — nous ne demanderons que quelques informations au téléchargement.",
    subscribeLabel: "S'abonner à la Dispatch",
    newsletterNote: "Vous la préférez dans votre boîte mail ? Abonnez-vous et nous vous enverrons un mot de confirmation — rédigé par toute l'équipe de The Dieng Group.",
    subscribedThanks: "Merci — vérifiez votre boîte mail pour confirmer votre inscription. Le mot est signé par toute l'équipe.",
    modalTitle: "Quelques informations, et il est à vous.",
    modalDoneKicker: "Prêt",
    modalDoneTitle: "Votre exemplaire arrive.",
    modalDoneBody: "The Meridian Dispatch, Numéro 01 se téléchargerait maintenant — et une confirmation arriverait dans votre boîte mail.",
    optIn: "Envoyez-moi aussi la newsletter (double opt-in — nous confirmerons par e-mail).",
  },
  podcast: {
    kicker: "À l'antenne",
    title: "Depuis le corridor, à voix haute.",
    standfirst: "Des conversations depuis le bureau et le terrain — ce que nous entendons sur les marchés et dans les ministères, en mots simples.",
    comingSoon: "Bientôt",
    episodes: [
      "Lire le terrain avant l'accord",
      "Un prix juste comme stratégie d'entreprise",
      "Ce que les gouvernements comprennent mal sur l'investissement",
    ],
  },
  contact: {
    kicker: "Contact",
    sectionKicker: "Contact",
    title: "Dites-nous où vous opérez. Nous vous y rejoindrons.",
    standfirst: "La première question que nous posons n'est jamais « quel est votre budget » — c'est « quel est le terrain sur lequel vous êtes ».",
    homeDesk: "Bureau principal",
    corridor: "Sur le corridor",
    reach: "Nous joindre",
    nameLabel: "Votre nom",
    emailLabel: "E-mail",
    orgLabel: "Type d'organisation",
    needLabel: "Ce qui vous amène",
    regionLabel: "Où vous opérez",
    tierLabel: "Échelle de la mission",
    msgLabel: "Un mot sur le projet",
    msgPlaceholder: "Que cherchez-vous à faire, et où ?",
    send: "Envoyer votre message",
    expandingNote: "En expansion vers l'Afrique de l'Est · l'Europe · l'Inde.",
    sentTitle: "Merci — votre message est bien arrivé.",
    sentBody: "Quelqu'un de l'équipe vous répondra, pas un robot. À très vite.",
    select: "Choisir…",
  },
  forms: {
    fullName: "Nom complet",
    sector: "Secteur / profession",
    phone: "Numéro de téléphone",
    emailAddress: "Adresse e-mail",
  },
  sectors: ["Privé / Entreprise", "ONG / Association", "Agence gouvernementale", "Éducation", "Santé", "Finance", "Agriculture & commerce", "Autre"],
  probing: {
    orgType: ["Privé / Entreprise", "ONG / Association", "Agence gouvernementale", "Autre"],
    need: ["Gestion de programmes & subventions", "Planification des effectifs", "Conduite du changement", "Conformité & audit", "Reporting & analyse de données", "Investissement direct étranger", "Politiques & gouvernance", "Contractualisation & négociation", "Diligence raisonnable", "Import / export"],
    region: ["États-Unis", "Sénégal", "Gambie", "Afrique de l'Ouest (autre)", "Afrique de l'Est", "Haïti / Caraïbes", "Europe", "Inde", "Autre"],
    engagement: ["Silver", "Gold", "Platinum", "Diamond", "Pas encore sûr"],
  },
  footer: {
    blurb: "Un cabinet de conseil, d'import et d'export qui travaille le corridor entre le Midwest américain et l'Afrique de l'Ouest.",
    sections: "Sections",
    desk: "Le bureau",
    rights: "Tous droits réservés.",
  },
  b2: {
    serveTitle: "Trois secteurs, une approche rigoureuse.",
    servicesTitle: "Des compétences réparties en trois grands domaines.",
    impactTitle: "Mesuré aux résultats, pas aux chiffres.",
    teamTitle: "Des conseillers qui ont fait le travail.",
    teamLead: "Une équipe à l'aise dans les secteurs privé, civil et public — et sur les marchés que nous servons.",
    aboutEyebrow: "Qui nous sommes",
    aboutTitle: "Trois branches, un seul but.",
    aboutLead: "The Dieng Group est un cabinet de conseil, d'import et d'export basé à Indianapolis, qui œuvre à rapprocher les organisations des marchés en développement du monde avec lequel elles commercent.",
    coreValues: "Nos valeurs",
  },
};

export const content: Record<Locale, typeof en> = { en, fr };
export type Content = typeof en;
